services:
  - type: web
    name: ig-dm-bot
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node sendDm.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: IG_SESSION_ID
        sync: false  # This will be set manually in Render dashboard
    healthCheckPath: /
    autoDeploy: true
    branch: main
